# #redis-slave
# - name: ip
#   set_fact:
#       slave_ip={{ansible_ssh_host}}
- name:  copy and  backup redis-config Master server
##remember to set variable inline to correct config per ip
  template: 
    src: redis-slave.conf.j2
    dest: /etc/redis.conf
    owner: redis  
    force: yes  
  tags: tempd
- name:  copy and  backup redis_sentinel-config Master server
##remember to set variable inline to correct config per ip
  template: 
    src: redis-sentinel-slave.conf.j2
    dest: /etc/redis-sentinel.conf
    owner: redis  
    force: yes
  tags: tempd   

